[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc = "0.8.27"
remappings = [
    "@layerzerolabs/lz-evm-protocol-v2=lib/LayerZero-v2/packages/layerzero-v2/evm/protocol/",
    "@layerzerolabs/lz-evm-oapp-v2=lib/LayerZero-v2/packages/layerzero-v2/evm/oapp/",
    "@layerzerolabs/lz-evm-messagelib-v2=lib/LayerZero-v2/packages/layerzero-v2/evm/messagelib/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin=lib/openzeppelin-contracts/",
    "solidity-bytes-utils/contracts=lib/solidity-bytes-utils/contracts/",
    "@layerzerolabs/lz-evm-v1-0.7/=node_modules/@layerzerolabs/lz-evm-v1-0.7/",
    "hardhat-deploy/solc_0.8/=node_modules/hardhat-deploy/solc_0.8/",
    "@chainlink/contracts-ccip/=lib/chainlink-local/lib/ccip/contracts",
]


[rpc_endpoints]
ethereumSepolia = "${ETHEREUM_SEPOLIA_RPC_URL}"
optimismGoerli = "${OPTIMISM_GOERLI_RPC_URL}"
avalancheFuji = "${AVALANCHE_FUJI_RPC_URL}"
arbitrumSepolia = "${ARBITRUM_SEPOLIA_RPC_URL}"
polygonMumbai = "${POLYGON_MUMBAI_RPC_URL}"
bnbChainTestnet = "${BNB_CHAIN_TESTNET_RPC_URL}"
baseSepolia = "${BASE_SEPOLIA_RPC_URL}"
metisSepolia = "${METIS_SEPOLIA_RPC_URL}"
zksyncSepolia = "${ZKSYNC_SEPOLIA_RPC_URL}"

