[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc = "0.8.27"
remappings = [
    "@layerzerolabs/lz-evm-protocol-v2=lib/LayerZero-v2/packages/layerzero-v2/evm/protocol/",
    "@layerzerolabs/lz-evm-oapp-v2=lib/LayerZero-v2/packages/layerzero-v2/evm/oapp/",
    "@openzeppelin=lib/openzeppelin-contracts/"
]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
